<form action="http://cva/ps/retorno" method="post" id="pagseguro" name="pagseguro">
	<input type="hidden" name="VendedorEmail" value="jahio@jahio.com" />
	<input type="hidden" name="TransacaoID" value="5904D5474A4F4AAB9C7B9B952A7EE0A6" />
	<input type="hidden" name="Referencia" value="" />
	<input type="hidden" name="Extras" value="0,00" />
	<input type="hidden" name="TipoFrete" value="FR" />
	<input type="hidden" name="ValorFrete" value="0,00" />
	<input type="hidden" name="Anotacao" value="" />
	<input type="hidden" name="DataTransacao" value="31/05/2013 17:51:23" />
	<input type="hidden" name="TipoPagamento" value="Cartão de Crédito" />
	<input type="hidden" name="StatusTransacao" value="Completo" />
	<input type="hidden" name="CliNome" value="Márcio Roberto Oliveira Aureliano dos Santos" />
	<input type="hidden" name="CliEmail" value="marcio.roas@gmail.com" />
	<input type="hidden" name="CliEndereco" value="RUA MONTE BELEM DE CIMA" />
	<input type="hidden" name="CliNumero" value="02" />
	<input type="hidden" name="CliComplemento" value="" />
	<input type="hidden" name="CliBairro" value="Engenho Velho de Brotas" />
	<input type="hidden" name="CliCidade" value="SALVADOR" />
	<input type="hidden" name="CliEstado" value="BA" />
	<input type="hidden" name="CliCEP" value="40243180" />
	<input type="hidden" name="CliTelefone" value="71 34895146" />
	<input type="hidden" name="ProdID_1" value="jahio_19" />
	<input type="hidden" name="ProdDescricao_1" value="Curso Menu Dinïmico com Nïveis de Acesso" />
	<input type="hidden" name="ProdValor_1" value="29.00" />
	<input type="hidden" name="ProdQuantidade_1" value="1" />
	<input type="hidden" name="ProdFrete_1" value="0,00" />
	<input type="hidden" name="ProdExtras_1" value="0,00" />
	<input type="hidden" name="NumItens" value="1" />
	<input type="hidden" name="Parcelas" value="1" />
	
	<input type="image" name="submit" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar.gif" alt="Pague com PagSeguro">
</form>