<form action="http://cva/ps/retorno" method="post" id="pagseguro" name="pagseguro">
	<input type="hidden" name="VendedorEmail" value="jahio@jahio.com" />
	<input type="hidden" name="TransacaoID" value="C6FB6B5156F14FBAAC1E3D82342057FB" />
	<input type="hidden" name="Referencia" value="" />
	<input type="hidden" name="Extras" value="0.0" />
	<input type="hidden" name="TipoFrete" value="FR" />
	<input type="hidden" name="ValorFrete" value="0.0" />
	<input type="hidden" name="Anotacao" value="" />
	<input type="hidden" name="DataTransacao" value="13/04/2013 08:44:05" />
	<input type="hidden" name="TipoPagamento" value="Cartão de Crédito" />
	<input type="hidden" name="StatusTransacao" value="Completo" />
	<input type="hidden" name="CliNome" value="Wagner Ramos Pereira" />
	<input type="hidden" name="CliEmail" value="wagner.ramos@superig.com.br" />
	<input type="hidden" name="CliEndereco" value="RUA DURVAL PEDROSO DA SILVA" />
	<input type="hidden" name="CliNumero" value="205" />
	<input type="hidden" name="CliComplemento" value="" />
	<input type="hidden" name="CliBairro" value="Vila do Castelo" />
	<input type="hidden" name="CliCidade" value="SAO PAULO" />
	<input type="hidden" name="CliEstado" value="SP" />
	<input type="hidden" name="CliCEP" value="04438220" />
	<input type="hidden" name="CliTelefone" value="" />
	<input type="hidden" name="ProdID_1" value="jahio_8" />
	<input type="hidden" name="ProdDescricao_1" value="Curso ADDT - Adobe Dreamweaver Developer Toolbox em Vïdeo Aulas" />
	<input type="hidden" name="ProdValor_1" value="69.00" />
	<input type="hidden" name="ProdQuantidade_1" value="1" />
	<input type="hidden" name="ProdFrete_1" value="0.00" />
	<input type="hidden" name="ProdExtras_1" value="0.00" />
	<input type="hidden" name="NumItens" value="1" />
	<input type="hidden" name="Parcelas" value="1" />
	
	<input type="image" name="submit" src="https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/120x53-pagar.gif" alt="Pague com PagSeguro">
</form>